server:
  port: 9004
spring: 
  data:
    mongodb.uri: mongodb://localhost:27017/twitter_media
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/followers_following_db
#    username: root
#    password: root
  application:
    name: MediaMS
  cloud:
    consul:
      hosting: localhost
      discovery:
        hostname: localhost